generator:
  class: sfDoctrineGenerator
  param:
    model_class:           VentaChatarra
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          venta_chatarra
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [detalle, monto, fecha]
        object_actions: []
      filter:  
        display: [ cliente_id]
      form:    ~
      edit:    ~
      new:     ~
