generator:
  class: sfDoctrineGenerator
  param:
    model_class:           cliente
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cliente
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
       title: clientes con mas compras
       display: [nombre, rut, direccion, tipo, total]
       object_actions: {}  
       actions: {}
       batch_actions: {}
       max_per_page: 10
      filter:
       display: [razon_social]
      form:    ~
      edit:    ~
      new:     ~
