generator:
  class: sfDoctrineGenerator
  param:
    model_class:           cliente
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cliente
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
       title: clientes con mas compras
       display: [razon_social,rut,direccion]
      filter:  
       display: [razon_social]
      form:    ~
      edit:    ~
      new:     ~
