generator:
  class: sfDoctrineGenerator
  param:
    model_class:           equipo
    theme:		         jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          equipo
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        origen:                   { label: Origen}
        marca:                    { label: Marca}
        peso:                     { label: Peso, help: formato peso en gramos: 2000}
        estado:                   { label: Estado}
        detalle:                  { label: Detalle}
        user_id:                  { label: Usuario }
        categoria_id:             { label: Categoría}
        empleado_id:              { label: Empleado}
        venta_equipo_id:          { label: Venta de Equipo }
      list:    
       title: Lista de Equipos
      filter:  
       display: [estado,marca]
      form:    ~
      edit:   
       title: Editar Equipo %%marca%%
       display:
         "Datos equipo": [id ,origen, marca, peso, estado, detalle, usuario_id, categoria_id, empleado_id, venta_equipo_id] 
      new:
       title: Ingresar Nuevo Equipo 
       display:
         "Datos equipo": [id ,origen, marca, peso, estado, detalle, usuario_id, categoria_id, empleado_id, venta_equipo_id] 
      show:
       title: Revisar Equipo
       display:
          "Datos equipo": [id ,origen, marca, peso, estado, detalle, usuario_id, categoria_id, empleado_id, venta_equipo_id] 
 
