<?php

/**
 * CategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object CategoriaTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Categoria');
    }

    public function getLitado() {
        $query = Doctrine_Query::create()
                ->addSelect("r.id, r.estado, r.marca, r.detalle")
                ->from("Categoria r")
                ->innerJoin("r.Piezas p")
                ->innerJoin("r.equipos e")
                ->addWhere('p.venta_pieza_id is null')
                ->andWhere('e.venta_equipo_id is null')
                ->fetchArray()
        ;
        return $query;
    }

}