<?php

/**
 * EquipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EquipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EquipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Equipo');
    }
    public function getLitadoEquipo(){
        $query = Doctrine_Query::create()
                ->addSelect("r.id, c.tipo as tipo, c.nombre_categoria as categoria, count(r.categoria_id) as cantidad")
                ->from("Equipo r")
                ->innerJoin("r.Categoria c")
                ->innerjoin("r.Usuario u")
                ->addWhere('r.venta_equipo_id is null')
                ->groupBy("r.marca")
                ->fetchArray()
        ;
                return $query;
    }
}