<?php

/**
 * VentaChatarraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VentaChatarraTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object VentaChatarraTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('VentaChatarra');
    }

    public function getLitado() {
        $query = Doctrine_Query::create()
                ->Select("r.id, r.monto as monto, r.fecha as fecha")
                ->from("VentaChatarra r")
                ->innerjoin("r.Containers c")
                ->innerJoin("c.Piezas p")
                ->Where('p.estado = ?', "Malo")
                ->fetchArray()
        ;
        return $query;
    }

}