generator:
  class: sfDoctrineGenerator
  param:
    model_class:           usuario
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          usuario
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        rut:                  { label: Rut, help : formato de rut: 11111111-1}
        nombres:              { label: Nombres}
        apellidos:            { label: Apellidos }
        email:                { label: Email, help: formato de email tunombre@tucorreo.com}
        fecha_nac:            { label: Fecha de Nacimiento}
        direccion:            { label: Direccion }
        ciudad_resirencia:    { label: Ciudad de Residencia}
        telefono:             { label: Telefono, help: Codigo de area + Numero telefono}
        fecha_contrato:       { label: Fecha Contrato }
        fecha_fin_contrato:   { label: Fecha Fin Contrato}
        sueldo:               { label: Sueldo}
        user_id:              { label: Usuario }
      list:   
       title: Lista de Usuarios
      filter:  
       display: [rut]
      form:    ~
      edit:    
       title: Editar Usuario %%nombres%% %%apellidos%%
      new:    
       title: Ingresar Nuevo Usuario
      show:
       title: Revisar Usuario