generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ventaequipo
    theme:		         jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ventaequipo
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        fecha:                 { label: Fecha}
        tipo:                  { label: Tipo}
        monto:                 { label: Monto }
        detalle:               { label: Detalle }

      list:   
        title: Ventas de Equipo
      filter:  
        display: [tipo, fecha]
      form:    ~
      edit:    
       title: Editar venta de equipo %%id%%
      new:
        title: Ingresar Nueva Venta
      show: 
        title: Revisar Venta