generator:
  class: sfDoctrineGenerator
  param:
    model_class:           categoria
    theme:		         jroller
    extra:		        [show, print, export]
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          categoria
    with_doctrine_route:   true
    actions_base_class:    sfActions


    config:
      actions: ~
      fields:  
        nombre_categoria:       { label: Nombre}
        descripcion:            { label: Descripción}
        tipo:                   { label: Tipo}
      list:    
        title: Lista de Categorías
        sort:          [nombre_categoria, asc]
      filter:  
       display: [nombre_categoria]
      form:    ~
      edit:    
         title: Editar Categoria %%nombre_categoria%% 
         display:
          "Datos Categorias": [nombre_categoria, descripcion,tipo]
      new:     
          title: Ingresar Categoria 
          display:
           "Datos Categorias": [nombre_categoria, descripcion,tipo]
      show :
          title: Revisar Categoria
          display:
            "Datos Categorias": [nombre_categoria, descripcion,tipo]
