generator:
  class: sfDoctrineGenerator
  param:
    model_class:           usuario
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          usuario
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
       
      fields:  ~
      list:    
       title: Consultar Usuario activos
       display: [rut, nombres, direccion, ciudad, telefono, email]
       object_actions: {}  
       actions: {}
       batch_actions: {}
       max_per_page: 10
      filter: 
       display: [user_id]	  
      form:    ~
      edit:    ~
      new:     ~
