<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/23 22:20:54
sfConfig::add(array(
  'mod_administrarequipos_enabled' => true,
  'mod_administrarequipos_view_class' => 'sfPHP',
));
