<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/23 18:44:54
sfConfig::add(array(
  'mod_administrarempleados_enabled' => true,
  'mod_administrarempleados_view_class' => 'sfPHP',
));
