<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/23 22:50:05
sfConfig::add(array(
  'mod_administrarventaequipo_enabled' => true,
  'mod_administrarventaequipo_view_class' => 'sfPHP',
));
