<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/23 22:20:22
sfConfig::add(array(
  'mod_administrarclientes_enabled' => true,
  'mod_administrarclientes_view_class' => 'sfPHP',
));
