<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/23 23:06:43
sfConfig::add(array(
  'mod_administrarventachatarra_enabled' => true,
  'mod_administrarventachatarra_view_class' => 'sfPHP',
));
