<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/23 23:00:26
sfConfig::add(array(
  'mod_administrarpiezas_enabled' => true,
  'mod_administrarpiezas_view_class' => 'sfPHP',
));
