<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/23 23:02:44
sfConfig::add(array(
  'mod_administrarventapieza_enabled' => true,
  'mod_administrarventapieza_view_class' => 'sfPHP',
));
