<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/23 23:08:13
sfConfig::add(array(
  'mod_administrarcontenedor_enabled' => true,
  'mod_administrarcontenedor_view_class' => 'sfPHP',
));
