<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/23 22:59:16
sfConfig::add(array(
  'mod_administrarcategorias_enabled' => true,
  'mod_administrarcategorias_view_class' => 'sfPHP',
));
