generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ventaequipo
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ventaequipo
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Consultar Ventas de Equipo
        display: [marca, estado, detalle,total]
        object_actions: {}  
        actions: {}
        batch_actions: {}
        max_per_page: 10
      filter: 
        display: [tipo]
      form:    ~
      edit:    ~
      new:     ~
