generator:
  class: sfDoctrineGenerator
  param:
    model_class:           cliente
    theme:		         jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cliente
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        rut:                { label: Rut}
        razon_social:       { label: Razón Social}
        giro:               { label: Giro }
        nombre_representante:  { label: Nombre Representante }
        direccion:          { label: Dirección }
        telefono_contacto:  { label: Teléfono de Contacto }
      list:    
        title: Listado de Clientes
        sort:          [rut, asc]
      filter:  
       display: [rut,giro]

      form:    ~
      edit:       
         title: Editar Cliente %%razon_social%% 
         display:
          "Datos Clientes": [rut,razon_social,giro,nombre_representante,direccion,telefono_contacto]
      new:     
       title: Ingresar Cliente 
       display:
         "Datos clientes": [rut,razon_social,giro,nombre_representante,direccion,telefono_contacto]
      show:
        title: Revisar Cliente
        display:
          "Datos clientes": [rut,razon_social,giro,nombre_representante,direccion,telefono_contacto]
