generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Container
    theme:		         jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          container
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        capacidad:                { label: Capacidad}
        tipo:                     { label: Tipo}
        venta_chatarra_id:        { label: Venta de Chatarra }

      list:    
        title: Lista de Contenedores
      filter:  
       display: [tipo]
      form:    ~
      edit:    
        title: Editar Contenedor %%id%%
        display:
          "Datos Contenedor": [capacidad,tipo]
      new:
        title: Ingresar Contenedor
        display:
          "Datos Contenedor": [capacidad, tipo,venta_chatarra_id]
      show:
        title: Revisar Contenedor
        display:
          "Datos Contenedor": [capacidad, tipo,venta_chatarra_id]