generator:
  class: sfDoctrineGenerator
  param:
    model_class:           pieza
    theme:		         jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pieza
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        marca:                   { label: Marca}
        estado:                  { label: Estado}
        detalle:                 { label: Detalle }
        user_id:                 { label: Usuario}
        categoria_id:            { label: Categoría}
        empleado_id:             { label: Empleado }
        container_id:            { label: Container }
        venta_pieza_id:          { label: Venta de Pieza }
      list:   
        title: Lista de Piezas
      filter:  
        display: [marca, categoria_id]
      form:    ~
      edit:    
       title: Editar pieza %%marca%%
      new:
        title: Ingresar Nueva Pieza
      show: 
        title: Revisar Piezas

