generator:
  class: sfDoctrineGenerator
  param:
    model_class:           empleado
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          empleado
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
       title: Empleados que reciben equipos
       display: [nombres, apellidos, user_id]
      filter:
       display: [rut]	  
      form:    ~
      edit:    ~
      new:     ~
