generator:
  class: sfDoctrineGenerator
  param:
    model_class:           VentaPieza
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          venta_pieza
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [monto, cliente, tipo, fecha]
        object_actions: []
        title: Listado de Ventas por Periodo
      filter:  
        display: [fecha]
      form:    ~
      edit:    ~
      new:     ~
