generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ventachatarra
    theme:		         jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ventachatarra
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        monto:                  { label: Monto}
        fecha:                  { label: Fecha}
        detalle:                { label: Detalle }
        tipo:                   { label: Tipo}
        cliente_id:             { label: Cliente}

      list:   
        title: Ventas de Chatarra
      filter:  
        display: [cliente_id, fecha]
      form:    ~
      edit:    
       title: Editar venta de chatarra %%id%%
      new:
        title: Ingresar Nueva Venta
      show: 
        title: Revisar Venta
