ventaequipo:
  class: sfDoctrineRouteCollection
  options:
    model:                ventaequipo
    module:               consultarVentaEquipo
    prefix_path:          /consultarVentaEquipo
    column:               id
    with_wildcard_routes: true

cliente:
  class: sfDoctrineRouteCollection
  options:
    model:                cliente
    module:               consultarCliente
    prefix_path:          /consultarCliente
    column:               id
    with_wildcard_routes: true
    
ventapieza:
  class: sfDoctrineRouteCollection
  options:
    model:                ventapieza
    module:               consultarVentaPieza
    prefix_path:          /consultarVentaPieza
    column:               id
    with_wildcard_routes: true
    
empleado:
  class: sfDoctrineRouteCollection
  options:
    model:                empleado
    module:               consultarEmpleado
    prefix_path:          /consultarEmpleado
    column:               id
    with_wildcard_routes: true

usuario:
  class: sfDoctrineRouteCollection
  options:
    model:                usuario
    module:               consultarUsuario
    prefix_path:          /consultarUsuario
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
