sfGuardUser:
  actAs: [Timestampable]
  columns:
    first_name: string(255)
    last_name: string(255)
    email_address:
      type: string(255)
      notnull: false
      unique: false
    username:
      type: string(128)
      notnull: true
      unique: true
    algorithm:
      type: string(128)
      default: sha1
      notnull: true
    salt: string(128)
    password: 
      type: string(128)
      notnull: true
    is_active:
      type: boolean
      default: 1
    is_super_admin:
      type: boolean
      default: false
    last_login:
      type: timestamp
  indexes:
    is_active_idx:
      fields: [is_active]
  relations:
    Groups:
      class: sfGuardGroup
      local: user_id
      foreign: group_id
      refClass: sfGuardUserGroup
      foreignAlias: Users
    Permissions:
      class: sfGuardPermission
      local: user_id
      foreign: permission_id
      refClass: sfGuardUserPermission
      foreignAlias: Users
    Empleado:
      local: id
      foreign: user_id
      type: one
    Usuario:
      local: id
      foreign: user_id
      type: one
    Clientes:
      local: id
      foreign: user_id
      type: one
	
Usuario:
  columns:
    id: 						{ type: integer(10), primary: true, notnull: true, autoincrement: true }
    rut:						{ type: string(10), notnull: true }
    nombres:					{ type: string(45), notnull: true }
    apellidos:					{ type: string(45), notnull: true }
    email:						{ type: string(45), notnull: true,unique: true }
    fecha_nac:					{ type: date }
    direccion:					{ type: string(45) }
    ciudad:						{ type: string(45) }
    user_id:					{ type: integer, fixed: false, unsigned: false, notnull: false, primary: false, unique: true}
  relations: 	
    sfGuardUser:
     local: user_id
     foreign: id
     type: one
	
	
Equipo:
  columns:
   id:         					{ type: integer(10), primary: true, notnull: true, autoincrement: true }
   origen:   					{ type: string(45) }
   marca:      					{ type: string(45), notnull:true }
   peso:       					{ type: integer(10) }
   estado:     					{ type: boolean, notnull:true }
   detalle:    					{ type: string(255) }
   user_id:						{ type: integer, fixed: false, unsigned: false, notnull: false, primary: false, unique: true}
   categoria_id: 				{ type: integer(10) }
   empleado_id: 				{ type: integer(10) }
   venta_equipo_id:				{ type: integer(10) }
  relations: 
   categoria: 					{ foreignAlias: equipos, onDelete: CASCADE } 
   empleado: 					{ foreignAlias: equipos, onDelete: CASCADE }
   VentaEquipo:                 { foreignAlias: equipos }
   sfGuardUser:
     local: user_id
     foreign: id
     type: one

VentaEquipo:
  columns:
    id:         				{ type: integer(10), primary: true, notnull: true, autoincrement: true }
    fecha:     					{ type: date,}
    tipo:       				{ type: string(45), notnull:true }
    monto:      				{ type: integer(10), notnull:true }
    detalle:    				{ type: string(255) }

Categoria:
  columns:
   id:               			{ type: integer(10), primary: true, notnull: true, autoincrement: true }
   nombre_categoria: 			{ type: string(45), notnull:true }
   descripcion:    				{ type: string(45), notnull:true } 
   tipo:             			{ type: string(45), notnull:true }

Pieza:
  columns:
    id:         				{ type: integer(10), primary: true, notnull: true, autoincrement: true }
    marca:      				{ type: string(45) }
    estado:     				{ type: boolean }
    detalle:    				{ type: string(45) }
    user_id:					{ type: integer, fixed: false, unsigned: false, notnull: false, primary: false, unique: true}
    categoria_id: 				{ type: integer(10) }
    empleado_id: 				{ type: integer(10) }
    container_id:				{ type: integer(10) }
    venta_pieza_id:				{ type: integer(10) }
  relations:   
    categoria: 					{ foreignAlias: Piezas, onDelete: CASCADE } 
    empleado: 					{ foreignAlias: Piezas, onDelete: CASCADE }
    container:                  { foreignAlias: Piezas, onDelete: CASCADE }
    VentaPieza:                 { foreignAlias: Piezas, onDelete: CASCADE }
    sfGuardUser:
      local: user_id
      foreign: id
      type: one

Empleado:
  columns:
    id:         				{ type: integer(10), primary: true, notnull: true, autoincrement: true }
    rut:        				{ type: string(10), notnull:true }
    nombres:    				{ type: string(45), notnull:true }
    apellidos:  				{ type: string(45), notnull:true }
    email:      				{ type: string(45), notnull:true,unique: true }        
    fecha_nac:  				{ type: timestamp }
    direccion:  				{ type: string(45) }
    ciudad_residencia:  		{ type: string(45) }
    telefono:          			{ type: integer(10), notnull:true }
    fecha_contrato:     		{ type: timestamp, notnull:true }
    fecha_fin_contrato: 		{ type: timestamp, notnull:true }
    sueldo:            			{ type: integer(10) }
    user_id:					{ type: integer, fixed: false, unsigned: false, notnull: false, primary: false, unique: true}
  relations:
    sfGuardUser:
      local: user_id
      foreign: id
      type: one

VentaPieza:
  columns:
    id:         				{ type: integer(10), primary: true, notnull: true, autoincrement: true }
    fecha:     					{ type: date, notnull:true }
    tipo:       				{ type: string(45), notnull:true }
    monto:     					{ type: integer(10), notnull:true }
    detalle:    				{ type: string(255) }
    cliente:    				{ type: string(45), notnull:true }
    gastos_envio: 				{ type: integer(10) }

VentaChatarra:
  columns:
    id:         				{ type: integer(10), primary: true, notnull: true, autoincrement: true }
    monto:      				{ type: integer(10), notnull:true }
    fecha:      				{ type: timestamp, notnull:true }
    detalle:   					{ type: string(255), notnull:true }
    tipo:      					{ type: string(45), notnull:true }
    cliente_id:					{ type: integer(10) }
  relations:
    cliente:					{ foreignAlias: VentaChatarras}

Container:
  columns:
    id:        					{ type: integer(10), primary: true, notnull: true, autoincrement: true } 
    capacidad: 					{ type: integer(10), notnull:true }
    tipo:      					{ type: string(45), notnull:true }
    venta_chatarra_id:			{ type: integer(10) }
  relations:
    VentaChatarra:			    { foreignAlias: Containers }

Cliente:
  columns:
    id:							{ type: integer(10), primary: true, notnull: true, autoincrement: true } 
    rut:        				{ type: string(10), notnull:true }
    razon_social:				{ type: string(45), notnull:true }
    giro:       				{ type: string(45), notnull:true }
    nombre_representante: 		{ type: string(45), notnull:true }
    direccion:          		{ type: string(45) }
    telefono_contacto:  		{ type: integer(45) }