generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ventapieza
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ventapieza
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:   
       title: Consultar Ventas Piezas
       display: [fecha, detalle, cliente]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
