generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ventapieza
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ventapieza
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:   
       title: Consultar Ventas Piezas
       display: [marca, fecha, detalle, cliente, categoria, total]
       object_actions: {}  
       actions: {}
       batch_actions: {}
       max_per_page: 10
      filter:  
       display: [tipo]
      form:    ~
      edit:    ~
      new:     ~
