generator:
  class: sfDoctrineGenerator
  param:
    model_class:           empleado
    theme:		         jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          empleado
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        rut:                  { label: Rut, help: formato de rut: 11111111-1}
        nombres:              { label: Nombres}
        apellidos:            { label: Apellidos }
        email:                { label: Email, help: formato de email tunombre@tucorreo.com}
        fecha_nac:            { label: Fecha de Nacimiento}
        direccion:            { label: Dirección }
        ciudad_residencia:    { label: Ciudad de Residencia}
        telefono:             { label: Teléfono, help: Código de área + Número teléfono}
        fecha_contrato:       { label: Fecha Contrato }
        fecha_fin_contrato:   { label: Fecha Fin Contrato}
        sueldo:               { label: Sueldo}
        user_id:              { label: Usuario }
      list:    
       title: Lista de Empleados
      filter:  
       display: [rut]
      form:    ~
      edit:   
       title: Editar Empleado
       display:
          "Datos Personales": [rut, nombres, apellidos, email, fecha_nac, direccion, ciudad_residencia, telefono, fecha_contrato, fecha_fin_contrato, sueldo]
      new:    
       title: Ingresar Empleado
       display:
          "Datos Personales": [rut, nombres, apellidos, email, fecha_nac, direccion, ciudad_residencia, telefono, fecha_contrato, fecha_fin_contrato, sueldo]
      show :
          title: Revisar Empleado
          display:
            "Datos Personales": [rut, nombres, apellidos, email, fecha_nac, direccion, ciudad_residencia, telefono, fecha_contrato, fecha_fin_contrato, sueldo, user_id]

