equipo:
  class: sfDoctrineRouteCollection
  options:
    model:                equipo
    module:               InvetarioEquipo
    prefix_path:          /InventarioEquipo
    column:               id
    with_wildcard_routes: true

excel:
  url:   /excel
  param: { module: ListadoInventario, action: excel }
  
excelEquipo:
  url:   /excelEquipo
  param: { module: InvetarioEquipo, action: excel }
   
pieza_ListadoInventario:
  class: sfDoctrineRouteCollection
  options:
    model:                Pieza
    module:               ListadoInventario
    prefix_path:          /ListadoInventario
    column:               id
    with_wildcard_routes: true

pieza:
  class: sfDoctrineRouteCollection
  options:
    model:                Pieza
    module:               ListadoInvetario
    prefix_path:          /ListadoInvetario
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
