# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            f4105a5b51f3b0e520986fa764b06745c742e94e
    enabled_modules: [default, sfGuardGroup, sfGuardUser, sfGuardPermission, sfGuardAuth]
    # Output escaping settings
    i18n: true
    default_culture: es
    default_timezone: "America/Santiago"
    compressed: on
    charset: utf-8
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database: true
    default_culture: es_ES
    default_user_culture: es_ES
    default_locale: es_ES
    default_user_locale: es_ES
  .actions:
    login_module: sfGuardAuth
    login_action: signin

    secure_module: sfGuardAuth
    secure_action: secure