generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ventapieza
    theme:		         jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ventapieza
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        fecha:                   { label: Fecha}
        tipo:                    { label: Tipo}
        monto:                   { label: Monto }
        detalle:                 { label: Detalle}
        cliente:                 { label: Cliente}
        gasto_envio:             { label: Gastos de Envío }
      list:   
        title: Lista de Ventas
      filter:  
        display: [tipo, fecha]
      form:    ~
      edit:    
       title: Editar venta %%id%%
      new:
        title: Ingresar Nueva venta
      show: 
        title: Revisar Venta